### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by iler** [wunderkraut/build.sh#13]
To make this properly open sourced let's add license for this project.

**Comment by iler** [comment]
@tcmug ping for this

**Comment by hugovk** [comment]
@iler This can be closed, the repo already contains a licence:

https://github.com/wunderkraut/build.sh/blob/develop/README.md#buildsh

> Released under GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007, see COPYING for details.

https://github.com/wunderkraut/build.sh/blob/develop/COPYING
