### ISSUE TITLE
Separate site.yml to two files to allow upstream updates

### ISSUE THREAD

**Issue by iler** [wunderkraut/build.sh#14]
The site.yml should be separated to two files:
- site.yml which would have the configurable parameters and variables
- commands.yml (or similar) which would have the non-configurable commands part

With this configuration we could then have commands.yml to be updated from upstream when we do some updates.

**Comment by tcmug** [comment]
Work started, see https://github.com/wunderkraut/build.sh/tree/commands

**Comment by tharna** [comment]
This is already done

**Comment by badrange** [comment]
And a lot of, if not all, the commands.yml I have seen are site specific - having custom commands executed on certain environments (stage, locals..) :-)

**Comment by tharna** [comment]
Site specific commands should be get in site.yml. We might start overwriting this at some point, so might be good idea to move them out there ;)
