### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by humansky** [wunderkraut/build.sh#21]
Now that Drupal is moving away from drush make and towards a composer build workflow, it would be nice if the build script can choose whether people want to build their Drupal site with composer or drush make.

**Comment by iler** [comment]
I think there is already some work in progress for the D8 related composer stuff. I think that @tcmug, @tharna or @mgalang can give you more precise answer for this.

**Comment by mgalang** [comment]
Yes. At least the development branch is working with composer project, but we need to add documentation regarding the directory and file structure.

**Comment by humansky** [comment]
I'll be happy to test if you give me a hint as to how to get it to build and install Drupal.

**Comment by tharna** [comment]
Closing, we already support composer based builds
