### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/build.sh#23]
After the latest commit to the develop branch https://github.com/wunderkraut/build.sh/commit/a618032ea4daefb9fa0088e0cb875f2213e11f89 I'm getting this error while trying to build:
`** BUILD ERROR: [Errno 2] No such file or directory: '/vagrant/drupal/current_bak'`

**Comment by tharna** [comment]
@aleksijohansson any special commands in your site.yml or commands.yml that might remove the final_build_dir before it's copied to that final_build_dir_bak?

**Comment by aleksijohansson** [comment]
@tharna The command I'm trying to run looks like this:

<pre>build:
  - make
  - backup:
      ignore:
        - sites/default/files
        - sites/cable-way.de/files
  - shell: chmod -R ug+w current
  - shell: unlink current/sites/default/files
  - purge
  - finalize
  - shell: cp conf/_ping.php current
  - shell: cp conf/Tuotteet_20122012.csv current
  - shell: patch --directory=current/sites/all/modules/contrib/quicktabs -p1 < conf/quicktabs-default_html_true.patch
  - shell: patch --directory=current/sites/all/modules/contrib/quicktabs -p1 < conf/quicktabs-fix-empty-tab-not-last.patch
  - shell: chmod -R a-w current</pre>

Do you see anything that could cause this issue?

**Comment by tharna** [comment]
@aleksijohansson it's that purge before finalize that already removes current build dir.
I'll add a check for that dir before attempting to remove it to prevent that error.

**Comment by mgalang** [comment]
Sorry, I'd like to re-open the issue. I'm still getting some issue related to this it seems:

*\* BUILD ERROR: [Errno 39] Directory not empty: '/vagrant/drupal/current_bak/web/core/assets/vendor/backbone'

This happens during the finalize task, it seems that it could not delete the vendor directory from the current_bak. Any idea why?

**Comment by tharna** [comment]
Probably d8 is downloading something to vendor folder, which therefore gets incorrect permisions / under nginx user so www-admin doesn't have permissions to remove those.
Need to investigate more with the d8 support.

**Comment by mgalang** [comment]
Closing this issue. It was a problem with the command.yml steps in local project :)

**Comment by badrange** [comment]
Is this a change that actually requires everybody to update their commands? Then I guess a heads up to everyone is in order?

**Comment by tharna** [comment]
@badrange no need for changes unless there are local commands defined.

**Comment by aleksijohansson** [comment]
@tharna I have local commands in some projects, what changes are needed?

**Comment by tharna** [comment]
@aleksijohansson it highly depends on the commands. In general you should check that the permissions are given correctly to any extra files loaded from external sources outside the drush make / composer install.

**Comment by aleksijohansson** [comment]
@tharna Ok, thanks for the info!

**Comment by badrange** [comment]
So we should inform everybody about the changes - so that people can check their own projects. I'll add a card to our Trello board about this :)
