### ISSUE TITLE
Hotfix command or check whether makefile has changed so we can ommit full build for small changes

### ISSUE THREAD

**Issue by tharna** [wunderkraut/build.sh#4]
When there is just some small changes to the custom code, features or theme there is no need to run the whole make process to get those changes in production.

Implementing either a 'hotfix' command that would only copy the code/\* folders to their respective places under current build dir or taking into use the makefile hash check when deciding if the full build is necessary would be nice.

**Comment by aleksijohansson** [comment]
I think this is already implemented in the newest version. The previous makes are saved and reused if the make file has not changed.

**Comment by tcmug** [comment]
Yes that's true :) drush make results are cached in a similar fashion in build.sh as they are in platform.sh.
