### ISSUE TITLE
Review and delete old branches

### ISSUE THREAD

**Issue by hugovk** [wunderkraut/build.sh#50]
There's quite a few old branches, many of which have been merged.

https://github.com/wunderkraut/build.sh/branches/all

It'd be good to review and delete those which are no longer needed.

![image](https://cloud.githubusercontent.com/assets/1324225/20878843/aa3d4c4a-bad9-11e6-8980-125c73082a60.png)

**Comment by tharna** [comment]
Cleaned up all the old branches and finally moved default branch to master
