### ISSUE TITLE
Install command results in error

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/build.sh#7]
Running the install command returns this error

*\* BUILD ERROR: execv() arg 2 must contain only strings

**Comment by aleksijohansson** [comment]
This can be bypassed by setting the install step manually like this:

<pre>- shell: cd current && drush -y si install_profile_name</pre>

**Comment by tcmug** [comment]
Which version of drush were you running at the time?

**Comment by aleksijohansson** [comment]
Version 7, but can't remember the exact version for sure.

**Comment by tharna** [comment]
Is this still relevant @aleksijohansson

**Comment by hugovk** [comment]
I guess this can be closed if it's no longer an issue and cannot be reproduced.

**Comment by tharna** [comment]
Agree
