### ISSUE TITLE
Build.sh fails to update custom code if set to copy

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/build.sh#8]
We have a project where build.sh is set to copy features etc. on build update. The newest version of build.sh fails since it packs the old build and then unpacks it and uses the old code. Using link instead of copy works for now, but this is something that should be fixed.

**Comment by tcmug** [comment]
Care to share what exactly is done? :)

**Comment by aleksijohansson** [comment]
Sure, sorry for the vague issue description! I was using the default copy of features etc. provided by the build.sh example:

<pre>
# Production environment:
production:
  aliases: prod
  # Prod environment only symlinks files
  link:
    - files: sites/default/files
  # Other files are copied, note settings.php
  copy:
    - code/modules/custom: sites/all/modules/custom
    - code/modules/features: sites/all/modules/features
    - code/themes/custom: sites/all/themes/custom
    - code/profiles/wk: profiles/wk
    - conf/prod.settings.php: sites/default/settings.php
</pre>

This failed to update the features for example when the make file wasn't changed and the previous build was unpacked and used.

**Comment by tcmug** [comment]
Btw. the newest version caches only the result of the drush make not the build itself.
Also there is now a switch to skip using this cache (-d or --disable-cache), hope these help :)
edit: newest version meaning develop

**Comment by aleksijohansson** [comment]
It seems this is now fixed.
