### ISSUE TITLE
Shell doesn't fail build if command exited with non-zero status code.

### ISSUE THREAD

**Issue by guncha25** [wunderkraut/build.sh#80]
If shell command can not be executed build process continues and may cause build to die later on process or finish successfully when actually something went wrong . That makes it harder to debug.  This should be changed so that build fails with message of command that failed.

**Comment by guncha25** [comment]
This is part of conversation in https://github.com/wunderkraut/WunderTools/pull/173

**Comment by tharna** [comment]
Resolved by #81
