### ISSUE TITLE
Use unlink on symbolic links inside builddir before removing old build

### ISSUE THREAD

**Issue by tharna** [wunderkraut/build.sh#9]
rmtree seems to try to follow symlic and tries to remove eg. files/ resulting either data loss or build error with "operation not permitted.'

**Comment by tharna** [comment]
Maybe before removing current build unlink all symlinks defined in site.yml?

**Comment by aleksijohansson** [comment]
Ran into this issue today, fix would definitely be welcome here!

**Comment by aleksijohansson** [comment]
Updated to the newest version today but still getting "operation not permitted" error on the files symlink. Is it needed to add something manually to the command stack or should this work automatically as part of the finalize step?

**Comment by tharna** [comment]
@aleksijohansson should work out of the box with latest version.
Sometimes there might be a situation where the files folder is already unlinked, but before the old build folder is deleted drupal creates the files folder while generating the derivate css-, js- or image files and in that case www-admin user doesn't have the permission to remove them anymore.
Next time this happens could you check that the files is indeed still a symlink, or is it just a regular folder with only few files inside (styles, css, js etc.).

**Comment by badrange** [comment]
I saw that just yesterday when deploying, don't remember if it was Tekla or Zenitel but I saw it! Scratched my head, deleted the thing and ran the build again.

**Comment by badrange** [comment]
I mean that I saw a folder with a few drupal-generated files in it

**Comment by aleksijohansson** [comment]
This is fixed in the latest version of build.sh site.yml examples.
